/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void add() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.add(1, 2));
    }
}
