/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateTodoRequest {
  title?: string;
  description?: string;
  dueDate?: string;
}
