/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TodoView {
  id?: string;
  title?: string;
  description?: string;
  completed?: boolean;
  dueDate?: string;
}
