/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTodoRequest,
  CreateTodoResponse,
  TodoView,
  UpdateTodoRequest
} from './schemas';





export type updateTodoResponse200 = {
  data: void
  status: 200
}
    
export type updateTodoResponseSuccess = (updateTodoResponse200) & {
  headers: Headers;
};
;

export type updateTodoResponse = (updateTodoResponseSuccess)

export const getUpdateTodoUrl = (id: string,) => {


  

  return `http://localhost:8080/api/todos/${id}/update`
}

export const updateTodo = async (id: string,
    updateTodoRequest: UpdateTodoRequest, options?: RequestInit): Promise<updateTodoResponse> => {
  
  const res = await fetch(getUpdateTodoUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTodoRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTodoResponse
}




export const getUpdateTodoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext> => {

const mutationKey = ['updateTodo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTodo>>, {id: string;data: UpdateTodoRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTodo(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodo>>>
    export type UpdateTodoMutationBody = UpdateTodoRequest
    export type UpdateTodoMutationError = unknown

    export const useUpdateTodo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTodo>>,
        TError,
        {id: string;data: UpdateTodoRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type completeTodoResponse200 = {
  data: void
  status: 200
}
    
export type completeTodoResponseSuccess = (completeTodoResponse200) & {
  headers: Headers;
};
;

export type completeTodoResponse = (completeTodoResponseSuccess)

export const getCompleteTodoUrl = (id: string,) => {


  

  return `http://localhost:8080/api/todos/${id}/complete`
}

export const completeTodo = async (id: string, options?: RequestInit): Promise<completeTodoResponse> => {
  
  const res = await fetch(getCompleteTodoUrl(id),
  {      
    ...options,
    method: 'PUT'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: completeTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as completeTodoResponse
}




export const getCompleteTodoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTodo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof completeTodo>>, TError,{id: string}, TContext> => {

const mutationKey = ['completeTodo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeTodo>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  completeTodo(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof completeTodo>>>
    
    export type CompleteTodoMutationError = unknown

    export const useCompleteTodo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTodo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeTodo>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCompleteTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type getAllTodosResponse200 = {
  data: TodoView[]
  status: 200
}
    
export type getAllTodosResponseSuccess = (getAllTodosResponse200) & {
  headers: Headers;
};
;

export type getAllTodosResponse = (getAllTodosResponseSuccess)

export const getGetAllTodosUrl = () => {


  

  return `http://localhost:8080/api/todos`
}

export const getAllTodos = async ( options?: RequestInit): Promise<getAllTodosResponse> => {
  
  const res = await fetch(getGetAllTodosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllTodosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllTodosResponse
}





export const getGetAllTodosQueryKey = () => {
    return [
    `http://localhost:8080/api/todos`
    ] as const;
    }

    
export const getGetAllTodosQueryOptions = <TData = Awaited<ReturnType<typeof getAllTodos>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTodosQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTodos>>> = ({ signal }) => getAllTodos({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTodos>>>
export type GetAllTodosQueryError = unknown


export function useGetAllTodos<TData = Awaited<ReturnType<typeof getAllTodos>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTodos>>,
          TError,
          Awaited<ReturnType<typeof getAllTodos>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTodos<TData = Awaited<ReturnType<typeof getAllTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTodos>>,
          TError,
          Awaited<ReturnType<typeof getAllTodos>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTodos<TData = Awaited<ReturnType<typeof getAllTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllTodos<TData = Awaited<ReturnType<typeof getAllTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTodos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTodosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type createTodoResponse200 = {
  data: CreateTodoResponse
  status: 200
}
    
export type createTodoResponseSuccess = (createTodoResponse200) & {
  headers: Headers;
};
;

export type createTodoResponse = (createTodoResponseSuccess)

export const getCreateTodoUrl = () => {


  

  return `http://localhost:8080/api/todos`
}

export const createTodo = async (createTodoRequest: CreateTodoRequest, options?: RequestInit): Promise<createTodoResponse> => {
  
  const res = await fetch(getCreateTodoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTodoRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTodoResponse
}




export const getCreateTodoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext> => {

const mutationKey = ['createTodo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTodo>>, {data: CreateTodoRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTodo(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof createTodo>>>
    export type CreateTodoMutationBody = CreateTodoRequest
    export type CreateTodoMutationError = unknown

    export const useCreateTodo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTodo>>,
        TError,
        {data: CreateTodoRequest},
        TContext
      > => {

      const mutationOptions = getCreateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type getTodoResponse200 = {
  data: TodoView
  status: 200
}
    
export type getTodoResponseSuccess = (getTodoResponse200) & {
  headers: Headers;
};
;

export type getTodoResponse = (getTodoResponseSuccess)

export const getGetTodoUrl = (id: string,) => {


  

  return `http://localhost:8080/api/todos/${id}`
}

export const getTodo = async (id: string, options?: RequestInit): Promise<getTodoResponse> => {
  
  const res = await fetch(getGetTodoUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTodoResponse
}





export const getGetTodoQueryKey = (id?: string,) => {
    return [
    `http://localhost:8080/api/todos/${id}`
    ] as const;
    }

    
export const getGetTodoQueryOptions = <TData = Awaited<ReturnType<typeof getTodo>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodo>>> = ({ signal }) => getTodo(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodoQueryResult = NonNullable<Awaited<ReturnType<typeof getTodo>>>
export type GetTodoQueryError = unknown


export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTodo<TData = Awaited<ReturnType<typeof getTodo>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type deleteTodoResponse200 = {
  data: void
  status: 200
}
    
export type deleteTodoResponseSuccess = (deleteTodoResponse200) & {
  headers: Headers;
};
;

export type deleteTodoResponse = (deleteTodoResponseSuccess)

export const getDeleteTodoUrl = (id: string,) => {


  

  return `http://localhost:8080/api/todos/${id}`
}

export const deleteTodo = async (id: string, options?: RequestInit): Promise<deleteTodoResponse> => {
  
  const res = await fetch(getDeleteTodoUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteTodoResponse
}




export const getDeleteTodoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTodo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodo>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTodo(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodo>>>
    
    export type DeleteTodoMutationError = unknown

    export const useDeleteTodo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTodo>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
