/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateTodoResponse,
  TodoView
} from './schemas';


export const getGetAllTodosResponseMock = (): TodoView[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().split('T')[0], undefined])})))

export const getCreateTodoResponseMock = (overrideResponse: Partial< CreateTodoResponse > = {}): CreateTodoResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), ...overrideResponse})

export const getGetTodoResponseMock = (overrideResponse: Partial< TodoView > = {}): TodoView => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().split('T')[0], undefined]), ...overrideResponse})


export const getUpdateTodoMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/todos/:id/update', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getCompleteTodoMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/todos/:id/complete', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetAllTodosMockHandler = (overrideResponse?: TodoView[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TodoView[]> | TodoView[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/todos', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllTodosResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateTodoMockHandler = (overrideResponse?: CreateTodoResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateTodoResponse> | CreateTodoResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/todos', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetTodoMockHandler = (overrideResponse?: TodoView | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TodoView> | TodoView), options?: RequestHandlerOptions) => {
  return http.get('*/api/todos/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteTodoMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/todos/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getOpenAPIDefinitionMock = () => [
  getUpdateTodoMockHandler(),
  getCompleteTodoMockHandler(),
  getGetAllTodosMockHandler(),
  getCreateTodoMockHandler(),
  getGetTodoMockHandler(),
  getDeleteTodoMockHandler()
]
